Various PEP8 fixes and test against py36
- E125 continuation line with same indent as next logical line
- E126 continuation line over-indented for hanging indent
- E127 continuation line over-indented for visual indent
- E261 at least two spaces before inline comment
- E301 expected 1 blank line
- E302 expected 2 blank lines
- E303 too many blank lines
- E502 the backslash is redundant between brackets
- E712 comparison to False should be 'if cond is False:' or 'if not cond:'
- E722 do not use bare 'except'
- E999 SyntaxError: invalid syntax
- F811 redefinition of unused 'sys' and 'get_color_from_hex'
- W293 blank line contains whitespace